[workspace]
resolver = "2"
members = ["rule_rs", "examples/*"]
default-members = ["rule_rs"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Panda <simple_95@163.com>"]
license = "MIT"
