cargo run --example all_components
cargo run --example all_nodes
cargo run --example aop_example
cargo run --example chain_management
cargo run --example circular_chain
cargo run --example circular_subchain
cargo run --example circular_three_chains
cargo run --example custom_component
cargo run --example delay_example
cargo run --example filter_example
cargo run --example js_function_example
cargo run --example js_function_multi_nodes
cargo run --example js_transform
cargo run --example rest_client_branch
cargo run --example rest_client
cargo run --example schedule_example
cargo run --example simple_rule
cargo run --example switch_example
cargo run --example transform_example
cargo run --example weather_service
cargo run --example server