metrics:
  enabled: true
  port: 9100
  path: "/metrics"
  
labels:
  app: "rulego"
  env: "dev"

collectors:
  - type: "node"
    enabled: true
    prefix: "rulego_node_"
    
  - type: "chain"
    enabled: true
    prefix: "rulego_chain_"
    
  - type: "message"
    enabled: true 
    prefix: "rulego_msg_" 